export const GET_DATA = 'GET_DATA';
export const RECEIVE_DATA = 'RECEIVE_DATA';
export const LOAD_CREDENTIALS = 'LOAD_CREDENTIALS';
export const SET_CREDENTIALS = 'SET_CREDENTIALS';
export const SAVE_CREDENTIALS = 'SAVE_CREDENTIALS';
export const DELETE_CREDENTIALS = 'DELETE_CREDENTIALS';