export const PERSISTER_LOAD = 'PERSISTER_LOAD';
export const PERSISTER_SAVE = 'PERSISTER_SAVE';
export const PERSISTER_DELETE = 'PERSISTER_DELETE';
export const PERSISTER_RECEIVE = 'PERSISTER_RECEIVE';